install.packages("pacman")
pacman::p_load(tidyverse,xlsx)
calproj <- read_csv("GitHub/CaliforniaProjections/calproj.csv", 
                      col_types = cols(`Annual Average Percent Change` = col_number(), 
                      `Median Annual` = col_number(), `Median Hourly` = col_number(), 
                      `Percent Change 2014-2024` = col_number(), 
                      `SOC Code*` = col_character())) %>% janitor::clean_names()
calproj_clean <- calproj %>% 
  separate(soc_code, c("gen_ocp","spec")) %>%
  separate(spec, c("sub_cat","spec"), sep = 1)%>%
  filter(spec != "000" & spec != "100") %>%
  mutate(general_occupation = case_when(
    gen_ocp == "11" ~ "Management Occupations",
    gen_ocp == "13" ~ "Business and Financial Operations Occupations",
    gen_ocp == "15" ~ "Computer and Mathematical Occupations",
    gen_ocp == "17" ~ "Architecture and Engineering Occupations",
    gen_ocp == "19" ~ "Life, Physical, and Social Science Occupations",
    gen_ocp == "21" ~ "Community and Social Service Occupations",
    gen_ocp == "23" ~ "Legal Occupations", 
    gen_ocp == "25" ~ "Education, Training, and Library Occupations",
    gen_ocp == "27" ~ "Arts, Design, Entertainment, Sports, and Media Occupations",
    gen_ocp == "29" ~ "Healthcare Practitioners and Technical Occupations",
    gen_ocp == "31" ~ "Healthcare Support Occupations",
    gen_ocp == "33" ~ "Protective Service Occupations",
    gen_ocp == "35" ~ "Food Preparation and Serving Related Occupations",
    gen_ocp == "37" ~ "Building and Grounds Cleaning and Maintenance Occupations",
    gen_ocp == "39" ~ "Personal Care and Service Occupations",
    gen_ocp == "41" ~ "Sales and Related Occupations",
    gen_ocp == "43" ~ "Office and Administrative Support Occupations",
    gen_ocp == "45" ~ "Farming, Fishing, and Forestry Occupations",
    gen_ocp == "47" ~ "Construction and Extraction Occupations",
    gen_ocp == "49" ~ "Installation, Maintenance, and Repair Occupations",
    gen_ocp == "51" ~ "Production Occupations",
    gen_ocp == "53" ~ "Management Occupations",
    gen_ocp == "55" ~ "Transportation and Material Moving Occupations"),
   subtype = case_when(
    gen_ocp == "11" & sub_cat == "1" ~ "Top Executives",
    gen_ocp == "11" & sub_cat == "2" ~ "Advertising, Marketing, Promotions, Public Relations, and Sales Managers",
    gen_ocp == "11" & sub_cat == "3" ~ "Operations Specialties Managers",
    gen_ocp == "11" & sub_cat == "9" ~ "Other Management Occupations",
    gen_ocp == "13" & sub_cat == "1" ~ "Business Operations Specialists",
    gen_ocp == "13" & sub_cat == "2" ~ "Financial Specialists",
    gen_ocp == "15" & sub_cat == "1" ~ "Computer Occupations",
    gen_ocp == "15" & sub_cat == "2" ~ "Mathematical Science Occupations",
    gen_ocp == "17" & sub_cat == "1" ~ "Architects, Surveyors, and Cartographers",
    gen_ocp == "17" & sub_cat == "2" ~ "Engineers",
    gen_ocp == "17" & sub_cat == "3" ~ "Drafters, Engineering Technicians, and Mapping Technicians",
    gen_ocp == "19" & sub_cat == "1" ~ "Life Scientists",
    gen_ocp == "19" & sub_cat == "2" ~ "Physical Scientists",
    gen_ocp == "19" & sub_cat == "3" ~ "Social Scientists and Related Workers",
    gen_ocp == "19" & sub_cat == "4" ~ "Life, Physical, and Social Science Technicians",
    gen_ocp == "21" & sub_cat == "1" ~ "Counselors, Social Workers, and Other Community and Social Service Specialists",
    gen_ocp == "21" & sub_cat == "2" ~ "Religious Workers",
    gen_ocp == "23" & sub_cat == "1" ~ "Lawyers, Judges, and Related Workers",
    gen_ocp == "23" & sub_cat == "2" ~ "Legal Support Workers",
    gen_ocp == "25" & sub_cat == "1" ~ "Postsecondary Teachers",
    gen_ocp == "25" & sub_cat == "2" ~ "Preschool, Primary, Secondary, and Special Education School Teachers",
    gen_ocp == "25" & sub_cat == "3" ~ "Other Teachers and Instructors",
    gen_ocp == "25" & sub_cat == "4" ~ "Librarians, Curators, and Archivists",
    gen_ocp == "25" & sub_cat == "9" ~ "Other Education, Training, and Library Occupations",
    gen_ocp == "27" & sub_cat == "1" ~ "Art and Design Workers",
    gen_ocp == "27" & sub_cat == "2" ~ "Entertainers and Performers, Sports and Related Workers",
    gen_ocp == "27" & sub_cat == "3" ~ "Media and Communication Workers",
    gen_ocp == "27" & sub_cat == "4" ~ "Media and Communication Equipment Workers",
    gen_ocp == "29" & sub_cat == "1" ~ "Health Diagnosing and Treating Practitioners",
    gen_ocp == "29" & sub_cat == "2" ~ "Health Technologists and Technicians",
    gen_ocp == "29" & sub_cat == "9" ~ "Other Healthcare Support Occupations",
    gen_ocp == "31" & sub_cat == "1" ~ "Nursing, Psychiatric, and Home Health Aides",
    gen_ocp == "31" & sub_cat == "2" ~ "Occupational Therapy and Physical Therapist Assistants and Aides",
    gen_ocp == "31" & sub_cat == "9" ~ "Other Healthcare Support Occupations",
    gen_ocp == "33" & sub_cat == "1" ~ "Supervisors of Protective Service Workers",
    gen_ocp == "33" & sub_cat == "2" ~ "Fire Fighting and Prevention Workers",
    gen_ocp == "33" & sub_cat == "3" ~ "Law Enforcement Workers",
    gen_ocp == "33" & sub_cat == "9" ~ "Other Protective Service Workers",
    gen_ocp == "35" & sub_cat == "1" ~ "Supervisors of Food Preparation and Serving Workers",
    gen_ocp == "35" & sub_cat == "2" ~ "Cooks and Food Preparation Workers",
    gen_ocp == "35" & sub_cat == "3" ~ "Food and Beverage Serving Workers",
    gen_ocp == "35" & sub_cat == "9" ~ "Other Food Preparation and Serving Related Workers",
    gen_ocp == "37" & sub_cat == "1" ~ "Supervisors of Building and Grounds Cleaning and Maintenance Workers",
    gen_ocp == "37" & sub_cat == "2" ~ "Building Cleaning and Pest Control Workers",
    gen_ocp == "37" & sub_cat == "3" ~ "Grounds Maintenance Workers",
    gen_ocp == "39" & sub_cat == "1" ~ "Supervisors of Personal Care and Service Workers",
    gen_ocp == "39" & sub_cat == "2" ~ "Animal Care and Service Workers",
    gen_ocp == "39" & sub_cat == "3" ~ "Entertainment Attendants and Related Workers",
    gen_ocp == "39" & sub_cat == "4" ~ "Funeral Service Workers",
    gen_ocp == "39" & sub_cat == "5" ~ "Personal Appearance Workers",
    gen_ocp == "39" & sub_cat == "6" ~ "Baggage Porters, Bellhops, and Concierges",
    gen_ocp == "39" & sub_cat == "7" ~ "Tour and Travel Guides",
    gen_ocp == "39" & sub_cat == "9" ~ "Other Personal Care and Service Workers",
    gen_ocp == "41" & sub_cat == "1" ~ "Supervisors of Sales Workers",
    gen_ocp == "41" & sub_cat == "2" ~ "Retail Sales Workers",
    gen_ocp == "41" & sub_cat == "3" ~ "Sales Representatives, Services",
    gen_ocp == "41" & sub_cat == "4" ~ "Sales Representatives, Wholesale and Manufacturing",
    gen_ocp == "41" & sub_cat == "9" ~ "Other Sales and Related Workers",
    gen_ocp == "43" & sub_cat == "1" ~ "Supervisors of Office and Administrative Support Workers",
    gen_ocp == "43" & sub_cat == "2" ~ "Communications Equipment Operators",
    gen_ocp == "43" & sub_cat == "3" ~ "Financial Clerks",
    gen_ocp == "43" & sub_cat == "4" ~ "Information and Record Clerks",
    gen_ocp == "43" & sub_cat == "5" ~ "Material Recording, Scheduling, Dispatching, and Distributing Workers",
    gen_ocp == "43" & sub_cat == "6" ~ "Secretaries and Administrative Assistants",
    gen_ocp == "43" & sub_cat == "9" ~ "Other Office and Administrative Support Workers",
    gen_ocp == "45" & sub_cat == "1" ~ "Supervisors of Farming, Fishing, and Forestry Workers",
    gen_ocp == "45" & sub_cat == "2" ~ "Agricultural Workers",
    gen_ocp == "45" & sub_cat == "4" ~ "Forest, Conservation, and Logging Workers",
    gen_ocp == "47" & sub_cat == "1" ~ "Supervisors of Construction and Extraction Workers",
    gen_ocp == "47" & sub_cat == "2" ~ "Construction Trades Workers",
    gen_ocp == "47" & sub_cat == "3" ~ "Helpers, Construction Trades",
    gen_ocp == "47" & sub_cat == "4" ~ "Other Construction and Related Workers",
    gen_ocp == "47" & sub_cat == "5" ~ "Extraction Workers",
    gen_ocp == "49" & sub_cat == "1" ~ "Supervisors of Installation, Maintenance, and Repair Workers",
    gen_ocp == "49" & sub_cat == "2" ~ "Electrical and Electronic Equipment Mechanics, Installers, and Repairers",
    gen_ocp == "49" & sub_cat == "3" ~ "Vehicle and Mobile Equipment Mechanics, Installers, and Repairers",   
    gen_ocp == "49" & sub_cat == "9" ~ "Other Installation, Maintenance, and Repair Occupations",   
    gen_ocp == "51" & sub_cat == "1" ~ "Supervisors of Production Workers",   
    gen_ocp == "51" & sub_cat == "2" ~ "Assemblers and Fabricators",   
    gen_ocp == "51" & sub_cat == "3" ~ "Food Processing Workers",
    gen_ocp == "51" & sub_cat == "4" ~ "Metal Workers and Plastic Workers",
    gen_ocp == "51" & sub_cat == "5" ~ "Printing Workers",
    gen_ocp == "51" & sub_cat == "6" ~ "Textile, Apparel, and Furnishings Workers",
    gen_ocp == "51" & sub_cat == "7" ~ "Woodworkers",
    gen_ocp == "51" & sub_cat == "8" ~ "Plant and System Operators",
    gen_ocp == "51" & sub_cat == "9" ~ "Other Production Occupations",
    gen_ocp == "53" & sub_cat == "1" ~ "Supervisors of Transportation and Material Moving Workers",
    gen_ocp == "53" & sub_cat == "2" ~ "Air Transportation Workers",
    gen_ocp == "53" & sub_cat == "3" ~ "Motor Vehicle Operators",
    gen_ocp == "53" & sub_cat == "4" ~ "Rail Transportation Workers",
    gen_ocp == "53" & sub_cat == "5" ~ "Water Transportation Workers",
    gen_ocp == "53" & sub_cat == "6" ~ "Other Transportation Workers",
    gen_ocp == "53" & sub_cat == "7" ~ "Material Moving Workers"),
   work_experience = case_when(work_experience == "?5 years" ~ "More than 5 years",
                               work_experience == "<5 years" ~ "Less than 5 years",
                               work_experience == "None" ~ "No experience necessary"),
   entry_level_education = case_when(entry_level_education == "1" ~ "Doctoral or professional degree",
                                     entry_level_education == "2" ~ "Master's degree",
                                     entry_level_education == "3" ~ "Bachelor's degree",
                                     entry_level_education == "4" ~ "Associate's degree",
                                     entry_level_education == "5" ~ "Postsecondary non-degree award",
                                     entry_level_education == "6" ~ "Some college, no degree",
                                     entry_level_education == "7" ~ "High school diploma or equivalent",
                                     entry_level_education == "8" ~ "No formal educational credential"),
   on_the_job_training = case_when (on_the_job_training == "I/R" ~ "Internship/Residency",
                                    on_the_job_training == "APP" ~ "Apprenticeship",
                                    on_the_job_training == "LT OJT" ~ "Long-term on-the-job-training",
                                    on_the_job_training == "MT OJT" ~ "Moderate-term on-the-job-training",
                                    on_the_job_training == "ST OJT" ~ "Short-term on-the-job-training",
                                    on_the_job_training == "None" ~ "Apprenticeship"))
cleanest <- calproj_clean %>%
  unite("soc_cod", c(sub_cat,spec), sep = "") %>%
  unite("soc_code", c(gen_ocp,soc_cod), sep = "_") %>%
  select(soc_code, general_occupation,subtype,occupational_title,estimated_employment_2014,
         projected_employment_2024,percent_change_2014_2024,annual_average_percent_change,
         new_jobs,replace_ment_needs,total_jobs,median_hourly,median_annual,entry_level_education,
         work_experience,on_the_job_training) %>%
write_csv("C:/Users/Branly Mclanbry/Documents/GitHub/CaliforniaProjections/use.dat.csv")
